// Code generated by go-autowire. DO NOT EDIT.

package wire_test

import (
	"github.com/Just-maple/go-autowire/test"
	"github.com/Just-maple/go-autowire/test/test_b"
	test2 "github.com/Just-maple/go-autowire/test/test_b/test"
	test3 "github.com/Just-maple/go-autowire/test/test_b/test/test"
	test_b2 "github.com/Just-maple/go-autowire/test/test_b/test/test_b"
	test4 "github.com/Just-maple/go-autowire/test/test_b/test/test_b/test"
	"github.com/Just-maple/go-autowire/test/test_c"
	"github.com/google/wire"
)

var StructSet = wire.NewSet(
	wire.Struct(new(test.Test), "*"),

	wire.Struct(new(test.Test2), "*"),
	wire.Bind(new(test.TestInterface1), new(*test.Test2)),

	test.ConstTest3,

	test.NewTest4,

	wire.Struct(new(test_b.Test), "*"),

	wire.Struct(new(test_b.Test2), "*"),

	wire.Struct(new(test2.Test), "*"),

	wire.Struct(new(test2.Test2), "*"),

	wire.Struct(new(test3.Test), "*"),

	wire.Struct(new(test3.Test2), "*"),

	wire.Struct(new(test_b2.Test), "*"),

	wire.Struct(new(test_b2.Test2), "*"),

	wire.Struct(new(test4.Test), "*"),

	wire.Struct(new(test4.Test2), "*"),

	wire.Struct(new(test_c.Test), "*"),

	wire.Struct(new(test_c.Test2), "*"),
)
