// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wire_test

import (
	"github.com/Just-maple/go-autowire/test"
	test_b2 "github.com/Just-maple/go-autowire/test/test_b"
	test3 "github.com/Just-maple/go-autowire/test/test_b/test"
	test2 "github.com/Just-maple/go-autowire/test/test_b/test/test"
	"github.com/Just-maple/go-autowire/test/test_b/test/test_b"
	"github.com/Just-maple/go-autowire/test/test_c"
)

// Injectors from wire.go:

func InitTest() test.Test {
	testTest := test2.Test{}
	testTest2 := test2.Test2{}
	test2_2 := test3.Test2{
		Test2: testTest2,
	}
	test4 := test3.Test{
		Test:  testTest,
		Test2: testTest2,
		T2:    test2_2,
	}
	testTest3 := test.ConstTest3()
	test2_3 := test.Test2{
		Test3: testTest3,
	}
	testTest4 := test.NewTest4()
	test_bTest2 := test_b.Test2{
		Test2: test2_2,
	}
	test_bTest := test_b.Test{
		Test:  test4,
		Test2: test2_2,
		T2:    test_bTest2,
	}
	test2_4 := test_b2.Test2{
		Test: test_bTest,
	}
	test_cTest2 := test_c.Test2{
		T3: test2_4,
	}
	test_cTest := test_c.Test{
		Test2: test_cTest2,
	}
	test5 := test_b2.Test{
		Test2: test2_4,
		Test:  test4,
	}
	test2_5 := &test.Test2{
		Test3: testTest3,
	}
	test6 := test.Test{
		T4:    test4,
		Test2: test2_3,
		Test3: testTest3,
		Test4: testTest4,
		Test:  test_cTest,
		T1:    test5,
		T3:    test2_4,
		T2:    test_cTest2,
		T:     test2_5,
	}
	return test6
}
