// Code generated by go-autowire. DO NOT EDIT.

package autowire_gen

import (
	"github.com/Just-maple/go-autowire/example/dependencies"
	"github.com/google/wire"
)

var FuncSet = wire.NewSet(
	dependencies.UselessFunc,
)
