// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package autowire_gen

import (
	"github.com/Just-maple/go-autowire/example/dependencies"
	test_b2 "github.com/Just-maple/go-autowire/example/dependencies/test_b"
	test2 "github.com/Just-maple/go-autowire/example/dependencies/test_b/test"
	"github.com/Just-maple/go-autowire/example/dependencies/test_b/test/test"
	"github.com/Just-maple/go-autowire/example/dependencies/test_b/test/test_b"
	"github.com/Just-maple/go-autowire/example/dependencies/test_c"
)

// Injectors from wire.go:

func InitTest() dependencies.Test {
	testTest := test.Test{}
	testTest2 := test.Test2{}
	test2_2 := test2.Test2{
		Test2: testTest2,
	}
	test3 := test2.Test{
		Test:  testTest,
		Test2: testTest2,
		T2:    test2_2,
	}
	dependenciesTest3 := dependencies.ConstTest3()
	dependenciesTest2 := dependencies.Test2{
		Test3: dependenciesTest3,
	}
	test4 := dependencies.NewTest4()
	test_bTest2 := test_b.Test2{
		Test2: test2_2,
	}
	test_bTest := test_b.Test{
		Test:  test3,
		Test2: test2_2,
		T2:    test_bTest2,
	}
	test2_3 := test_b2.Test2{
		Test: test_bTest,
	}
	test_cTest2 := test_c.Test2{
		T3: test2_3,
	}
	test_cTest := test_c.Test{
		Test2: test_cTest2,
	}
	test5 := test_b2.Test{
		Test2: test2_3,
		Test:  test3,
	}
	test2_4 := &dependencies.Test2{
		Test3: dependenciesTest3,
	}
	dependenciesTest := dependencies.Test{
		T4:    test3,
		Test2: dependenciesTest2,
		Test3: dependenciesTest3,
		Test4: test4,
		Test:  test_cTest,
		T1:    test5,
		T3:    test2_3,
		T2:    test_cTest2,
		T:     test2_4,
	}
	return dependenciesTest
}
