// Code generated by go-autowire. DO NOT EDIT.

package example_zoo

import (
	"github.com/google/wire"
)

var AnimalsSet = wire.NewSet(
	wire.Struct(new(Bird), "*"),
	wire.Bind(new(FlyAnimal), new(*Bird)),

	wire.Struct(new(Cat), "*"),

	NewLion,

	ProvideDog,

	InitSomeTiger,
)
