// Code generated by go-autowire. DO NOT EDIT.

package example_zoo

import (
	"github.com/google/wire"
)

var ConfigSet = wire.NewSet(
	wire.FieldsOf(new(*Config),
		"AnonymousConfigField2",
		"ConfigField",
	),
)
