// Code generated by go-autowire. DO NOT EDIT.

// +build wireinject

package example_zoo

import "github.com/google/wire"

func InitializeMiniZoo() (*MiniZoo, func(), error) {
	panic(wire.Build(Sets))
}

func InitializeZoo() (*Zoo, func(), error) {
	panic(wire.Build(Sets))
}
