// Code generated by go-autowire. DO NOT EDIT.

//go:build wireinject
// +build wireinject

package example_zoo

import "github.com/google/wire"

func InitializeMiniZoo(c0 *Config) (*MiniZoo, func(), error) {
	panic(wire.Build(Sets))
}

func InitializeZoo(c0 *Config) (*Zoo, func(), error) {
	panic(wire.Build(Sets))
}
