// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package example_zoo

// Injectors from wire.gen.go:

func InitializeMiniZoo(c0 *Config) (*MiniZoo, func(), error) {
	cat := Cat{}
	bird := &Bird{}
	miniZoo := &MiniZoo{
		Cat:       cat,
		FlyAnimal: bird,
	}
	return miniZoo, func() {
	}, nil
}

func InitializeZoo(c0 *Config) (*Zoo, func(), error) {
	cat := Cat{}
	dog := ProvideDog()
	lion := NewLion()
	bird := &Bird{}
	configField := c0.ConfigField
	configField2 := c0.ConfigField2
	zoo := &Zoo{
		Cat:          cat,
		Dog:          dog,
		Lion:         lion,
		FlyAnimal:    bird,
		ConfigField:  configField,
		ConfigField2: configField2,
	}
	return zoo, func() {
	}, nil
}
