// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package example_zoo

// Injectors from wire.gen.go:

func InitializeMiniZoo(c0 *Config) (*MiniZoo, func(), error) {
	cat := Cat{}
	bird := &Bird{}
	miniZoo := &MiniZoo{
		Cat:       cat,
		FlyAnimal: bird,
	}
	return miniZoo, func() {
	}, nil
}

func InitializeZoo(c0 *Config) (*Zoo, func(), error) {
	cat := Cat{}
	dog := ProvideDog()
	lion := NewLion()
	bird := &Bird{}
	configField := c0.ConfigField
	anonymousConfigField2 := c0.AnonymousConfigField2
	tiger := InitSomeTiger()
	zoo := &Zoo{
		Cat:                   cat,
		Dog:                   dog,
		Lion:                  lion,
		FlyAnimal:             bird,
		ConfigField:           configField,
		AnonymousConfigField2: anonymousConfigField2,
		Tiger:                 tiger,
	}
	return zoo, func() {
	}, nil
}
