// Code generated by go-autowire. DO NOT EDIT.

package init_zoo

import (
	"github.com/Just-maple/go-autowire/example_zoo"
	"github.com/google/wire"
)

var AnimalsSet = wire.NewSet(
	wire.Struct(new(example_zoo.Bird), "*"),
	wire.Bind(new(example_zoo.FlyAnimal), new(*example_zoo.Bird)),

	wire.Struct(new(example_zoo.Cat), "*"),

	wire.Struct(new(example_zoo.Dog), "*"),
)
